### PR TITLE
Adds Windows Support

### LINKED ISSUE #27: Support for Windows boxes
It would be nice to be able to use this plugin to push CAs to Windows guests.

### PR DESCRIPTION
**Pull request by jakauppila**
Adds support for Windows.

This uploads the configured certificates to 'C:\ssl\certs' where they are then added to the LocalMachine Root CA store as well as merged within 'C:\ssl\cacert.pem' which we point 'SSL_CERT_FILE' to for Ruby to utilize.

Successfully tested with Windows Server 2012/2012R2/2016. Will not work for anything earlier due to the usage of '[Import-Certificate](https://technet.microsoft.com/en-us/library/hh848630.aspx)'.

Also bumped the version to 1.3.0.

Fixes #27

### CODE REVIEW

**Comment by Jakauppila** [comment]
@johnbellone @jsok @williambailey 

Need anything else from me for this?

**Comment by johnbellone** [comment]
Let me see if I can get someone to review this that has more expertise than I in windows.

**Comment by jjustice6** [comment]
We can't accept this for our usage because of Import-Certificate, but luckily I have an alternative for you. We do something like this elsewhere, and it works in older versions of Powershell.

```
Get-ChildItem -Path C:/ssl/certs |
Foreach-Object {
certutil -addstore -enterprise -f "Root" $_.FullName
}

```

https://technet.microsoft.com/en-us/library/cc732443(v=ws.11).aspx for details on certutil (which is, despite the identical name, completely unrelated to the "certutil" on linux that you use to manipulate firefox/chrome certificate databases... guess how I know this. ;)

If you make the change from Import-Certificate to certutil, I think we could probably merge.

The one thing I will caution here is that tons of random crap (mostly linuxy software with windows ports) that runs on Windows don't actually use the system certificate store but require you to point their configuration or an environment variable at a folder full of certs or the cacert.pem. (This isn't really any different than how it works on Linux, except on Linux everything's already pointing at the default locations.) So the user experience is still likely to be worse than on Linux, but this is of course better than it not working at all.

**Comment by Jakauppila** [comment]
@jjustice6 Thanks for the feedback, I'll get that updated and tested.

To your second point, yes, I agree that it is a bit of a mess, but that's also why it's handling importing the certificates into the Windows store as well as configuring the environment variable 'SSL_CERT_FILE' to point at the bundle which Ruby (and a number of other tools) utilize.

Since there is no standard file-based bundle location on Windows, I configured it to place them at 'C:/ssl/certs/', but I'd be open to a better suggestion.

**Comment by jjustice6** [comment]
I have no problem with that location. (John: we put ours in C:\ProgramData\(Our Program)\ because we're in a context where we don't necessarily want to overwrite anything in C:\, but in the vagrant context we know there's no chance there will be something in C:\ssl\ so it's safe to put something there.)

Other than that I think this is probably mergeable (I'll see if I can find some time to actually test it in our environment).

@Jakauppila After a bit of thought, there is one thing that comes to mind which would make this more usable - I know of at least one tool (git) which specifically insists on Unix line endings. Yes, even on Windows. No, I don't know why. We point ssl_cert_file to the windows-line-ending variant as that's more widely tolerated, but we also made a cacert_unix.pem with the Unix line endings. I wouldn't hold up a merge of this based on a lack of such, but it would (probably?) be better for usability if that existed as well.

**Comment by Jakauppila** [comment]
@jjustice6 Should anything point at the cacert_unix.pem or should it be up the the user to override 'SSL_CERT_FILE' when using those tools that require it?

**Comment by jjustice6** [comment]
Nah, you're going to need to set that in a gitconfig for git. SSL_CERT_FILE needs to point to the Windows-linebreak version because the vast majority of tools use that.

I certainly don't think it's the responsibility of this tool to set up certificates for every piece of software with its own bizarre method of managing certificates that isn't the system's (e.g. Chrome and Firefox with their crazy certdbs). And really, if it's a pain to change the line endings in powershell, then it can be skipped. It just seems like an obvious easy win to throw into the mix.

**Comment by Jakauppila** [comment]
Replaced Import-Certificate with certutil and added 'cacert_unix.pem' with the correct line endings.

I verified it's working with Server 2008R2 but wasn't able to get SSH or WinRM to work correctly communicating to a Server 2008 public Vagrant box ([opentable/win-2008-standard-amd64-nocm](https://atlas.hashicorp.com/opentable/boxes/win-2008-standard-amd64-nocm)), I don't think there's any reason why it wouldn't work there too.

**Comment by Jakauppila** [comment]
@jjustice6 Need anything else from me for this?

**Comment by jjustice6** [comment]
No, this looks fine. It just slipped off my radar by mistake.

@johnbellone this gets a :+1: from me.

**Comment by Jakauppila** [comment]
Just wanted to ping about this again.

**Comment by jakauppila** [comment]
Just wanted to follow up on this again.

**Pull request merged**
